Get http://localhost:5021/games

###
Get http://localhost:5021/games/20

###
POST http://localhost:5021/games
Content-Type: application/json

{
    "Name": "Super Mario",
    "Genre": "Platform",
    "Price": 59.99,
    "ReleaseDate": "2010-02-01"
}

###
PUT http://localhost:5021/games/3
Content-Type: application/json

{
    "Name": "Street Fighter 2 turbo",
    "Genre": "Fighting",
    "Price": 29.99,
    "ReleaseDate": "1999-07-15"
}

###

DELETE http://localhost:5021/games/1